Handle login, signup, forgot
quangpn0204/GemstonesBusinessManagementSystem pull request #6
Opened 2021-04-26 13:13 UTC by Luunguyen2412

login, signup, forgot

2021-05-05 07:54 UTC, baodv1001 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/Views/ForgotPasswordWindow.xaml
> +﻿<Window x:Class="GemstonesBusinessManagementSystem.Views.ForgotPasswordWindow"
chỗ này các thuộc tính xuống hàng giống format của mấy cái component bên dưới

2021-05-05 07:55 UTC, baodv1001 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/Views/LoginWindow.xaml
> +                Foreground="{StaticResource Primary}" Height="85" Width="231"/>
mỗi thuộc tính một hàng nhá

2021-05-05 08:06 UTC, baodv1001 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/ViewModels/LoginViewModel.cs
> +            ChangePasswordCommand = new RelayCommand<LoginWindow>((p) => true, (p) => openForgotPasswordWindow(p));
tên hàm ko bắt đầu bằng chữ thường

2021-05-05 08:06 UTC, baodv1001 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/ViewModels/LoginViewModel.cs
> +        public ICommand TurnOnNotiCommand { get; set; }
cái nào ko dùng thì xóa đi chứ, copy lại cũng cop cái cần thôi

2021-05-06 15:29 UTC, Luunguyen2412 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/Views/ForgotPasswordWindow.xaml
> +﻿<Window x:Class="GemstonesBusinessManagementSystem.Views.ForgotPasswordWindow"
ok

2021-05-17 01:53 UTC, quangpn0204 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/DAL/AccountDAL.cs
> +            DataTable result = new DataTable();
Hình như cái hàm này sai rồi

2021-05-17 01:53 UTC, quangpn0204 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/DAL/AccountDAL.cs
> +        {
Hình như cái hàm này sai rồi

2021-05-18 07:51 UTC, baodv1001 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/Views/LoginWindow.xaml
> +                    Padding="2,0,0,0" VerticalContentAlignment="Center">
xuống dòng chỗ này này

2021-05-18 13:17 UTC, trunghuynh2304 requested changes
Kiểm tra lại format code, Ctrl K D nha
Mấy file xaml để ý xuống dòng, có mấy chỗ dư dòng

2021-05-18 13:17 UTC, trunghq234 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/DAL/AccountDAL.cs
> +            string query = "SELECT * FROM Account WHERE idAccount = '" + idAccount + "' AND username = '" + userName + "' AND password = '" + passWord + "' and type " + type ;
sao ko dùng String.Format cho tiện?

2021-05-18 13:17 UTC, trunghq234 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/ViewModels/LoginViewModel.cs
> +        public void openForgotPasswordWindow(LoginWindow loginWindow)
sai convention nha

2021-05-18 13:17 UTC, trunghq234 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/DAL/AccountDAL.cs
> +            for (int i = 0; i < dt.Rows.Count; i++)
Cái này nếu vào catch rồi nó vẫn chạy tiếp thì sao? Này là chưa hiểu code rồi.

2021-05-18 13:17 UTC, trunghq234 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/DAL/AccountDAL.cs
> +        public int SetNewID()
Tên hàm khác với hành động thực hiện bên trong hàm. Tiền tố là set nhưng trong hàm là get.

2021-05-18 13:17 UTC, trunghq234 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/DAL/AccountDAL.cs
> +            catch { return false; }
=))

2021-05-18 13:17 UTC, trunghq234 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/DAL/AccountDAL.cs
> +                if (dt.Rows.Count == 1)
return dt.Row.Count == 1; 
nhanh hơn đó

2021-05-18 13:17 UTC, trunghq234 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/DAL/AccountDAL.cs
> +                string query = "select * from account where username  = '" + username + "'";
mấy cái như này thì dùng String.Format cho dễ viết, chỉnh sửa cũng dễ

2021-05-18 13:17 UTC, trunghq234 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/DAL/AccountDAL.cs
> +                if(dt.Rows.Count > 0)
Tương tự như trên.

2021-05-18 13:17 UTC, trunghq234 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/DAL/CustomerDAL.cs
> +            for(int i = 0; i < dt.Rows.Count; i++)
Lại sai chỗ này nữa nè.

2021-05-18 13:17 UTC, trunghq234 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/DAL/CustomerDAL.cs
> +        public Customer GetList(string idCustomers)   // lấy thông tin khách hàng khi biết id
Lấy 1 khách mà dùng "GetList"? 1 id của 1 khách mà tên biến là idCustomers

2021-05-18 13:17 UTC, trunghq234 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/DAL/CustomerDAL.cs
> +                string queryStr = "select * from Customer where idCustomer " + idCustomers ;
Code xong thì format lại code, Ctrl + K + D nha

2021-05-18 13:17 UTC, trunghuynh2304 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/DAL/CustomerDAL.cs
> +            for (int i = 0; i < dt.Rows.Count; i++)
Sai chỗ này nữa nha

2021-05-18 13:17 UTC, trunghuynh2304 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/DAL/CustomerDAL.cs
> +                }
Xem hàm GetMaxId bên EmployeeDAL nha, ko cần fill datatable vậy đâu

2021-05-18 13:17 UTC, trunghuynh2304 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/DAL/CustomerDAL.cs
> +        public void Count()
Hàm này dùng để làm gì vậy? Ko thấy sài?

2021-05-18 13:17 UTC, trunghuynh2304 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/ViewModels/CustomerViewModel.cs
> +        public ICommand OpenAddCustomerWinDowCommand { get; set; }
OpenAddCustomerWindowCommand chứ

2021-05-18 13:17 UTC, trunghuynh2304 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/ViewModels/CustomerViewModel.cs
> +            mainWindow.txtNumOfCus.Text = String.Format("{0} - {1} of {2} items", start == end ? 0 : start + 1, end, customerList.Count);
sửa này nha

2021-05-18 13:17 UTC, trunghuynh2304 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/ViewModels/CustomerViewModel.cs
> +        public void CountCustomer(MainWindow mainWindow)
Cái này có sử dụng ko?

2021-05-18 13:17 UTC, trunghuynh2304 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/ViewModels/LoginViewModel.cs
> +        private bool isLogin;
gom cho nó đi theo cặp nè

2021-05-18 13:17 UTC, trunghuynh2304 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/ViewModels/SignUpViewModel.cs
> +        private string passwordConfirm;
gom cho nó đi theo cặp, dễ kiểm soát nha

2021-05-18 13:17 UTC, trunghuynh2304 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/ViewModels/SignUpViewModel.cs
> +            }
Sao viết DAL trong này?

2021-05-18 13:17 UTC, trunghuynh2304 commented on GemstonesBusinessManagementSystem/GemstonesBusinessManagementSystem/ViewModels/SignUpViewModel.cs
> +            }
DAL nằm trong VM

2021-06-10 13:01 UTC, merged